version: '3.8'

services:
  app:
    build: .
    container_name: app
    image: app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mqtt5
    networks:
      - mqtt5-network
      
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    networks:
      - mqtt5-network
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -h localhost -t test -m test || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  config:
  data:
  log:

networks:
  mqtt5-network:
    driver: bridge
